---------------Fatal error---------------
"D:\Documents\GitHub\NewLifeUtils\test.py" (12): <module>
  > n()
"D:\Documents\GitHub\NewLifeUtils\test.py" (11): n
  > A()
"D:\Documents\GitHub\NewLifeUtils\test.py" (7): __init__
  > self.foo(0)
"D:\Documents\GitHub\NewLifeUtils\test.py" (9): foo
  > zero/zero
ZeroDivisionError: division by zero

---------------           ---------------
---------------Error---------------
"D:\Documents\GitHub\NewLifeUtils\test.py" (12): <module>
  > n()
"D:\Documents\GitHub\NewLifeUtils\test.py" (11): n
  > A()
"D:\Documents\GitHub\NewLifeUtils\test.py" (7): __init__
  > self.foo(0)
"D:\Documents\GitHub\NewLifeUtils\test.py" (9): foo
  > zero/zero
ZeroDivisionError: division by zero

---------------     ---------------
[18:21:28] [L] My Cmd  : Welcome to My CMD
[18:21:31] [R] My Cmd  : fuck
---------------Attention---------------
Traceback is disabled
More info: Why you so evil?...
:_(
TIP: you can be beter
---------------         ---------------
[18:32:06] [R] My Cmd  : 
[18:32:15] [R] My Cmd  : exit
[18:32:15] [L] My Cmd  : Exit with code: quit, from: None
